version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  test-api:
    docker:
      # replace with your preferred image
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
      - run:
          name: Run tests and collect coverage
          command: |
            coverage run test.py
            coverage xml
      - codecov/upload: 
          token: CODECOV_TOKEN

workflows:
  example-workflow:
    jobs:
      - test-api:
          context: my_context