@startuml deployment
skinparam Dpi 350
skinparam Monochrome true
skinparam Shadowing false

node <<device>>\nClientDevice as ClientDevice  { 
node <<executionEnvironment>>\nPython as Python {
    artifact <<Artifact>>\nGameClient as GameClient{

    }
    artifact <<Artifact>>\nAIAgentInterface as AIAgentInterface{

    }
    artifact <<Artifact>>\nGamePackage as GamePackage{

    }
}
database <<Artifact>>\nInventoryDatabase as InventoryDatabase {
    
}


file <<File>>\nWorldFallbackFile as WorldFile{

}

file <<File>>\nRecipes as Recipes {
    
}

file <<File>>\nGameConfig as Config {
    
}
folder <<Folder>>\nTextures as Textures {

}
folder <<Folder>>\nSounds as Sounds {

}
folder <<Folder>>\nGymEnvironment as GymEnvironment {

}
}
GameClient -- InventoryDatabase
GameClient -- WorldFile
GameClient -- Textures
GameClient -- Sounds
GameClient -- Recipes
GameClient -- Config
AIAgentInterface -- GymEnvironment
AIAgentInterface -- GameClient
@enduml