@startuml
[Game Settings]

[Crafting]
[Block]
[Item]
[Breaking and Placing]
[Player]
[Camera]
[Game World]
[Inventory]
[User Interface]
[Game Menu]
[Audio]
[AI Agent] #ADD8E6

folder "Files"{
    [Sprites]

}

folder "JSON Files"{
    [Item JSON]
    [Recipe JSON]
}
() "Get Texture" as GT1
() "Get Texture" as GT2
() "Get Texture" as GT3
[Sprites] -- GT1
GT1 )-- [Block]
[Sprites] -- GT3
GT3 )-- [Item]
[Sprites] -- GT2
GT2 )-- [Player]

() "Get Block Properties" as GBlockInfo
() "Get Item Properties" as GBItemInfo
[Block] --( GBlockInfo
GBlockInfo -- [Item JSON]
[Item] --( GBItemInfo
GBItemInfo -- [Item JSON]

() "Get Game Settings" as GGameSetting
[Game World] --( GGameSetting
GGameSetting -- [Game Settings]

() "Get Block" as GBlock
() "Get Item" as GItem

[Inventory] --( GBlock
GBlock -- [Block]
[Inventory] --( GItem
GItem -- [Item]

() "Store/Retrieve Block" as StoreRetrieveBlock
[Breaking and Placing] --( StoreRetrieveBlock
StoreRetrieveBlock -- [Inventory]

() "Select Item/Block" as SelectItemBlock
SelectItemBlock -- [Inventory]
[Player] --( SelectItemBlock

() "Break/Place Block" as BreakPlaceBlock
[Breaking and Placing] -- BreakPlaceBlock
BreakPlaceBlock )-- [Player]

() "Break/Place Block" as PlaceBlock
[Game World] -- PlaceBlock
[Breaking and Placing] --( PlaceBlock

() "Craft Item/Block" as Craft
[Crafting] -- Craft
[Player] --( Craft

() "Get Recipes" as GetRecipes
[Crafting] --( GetRecipes
[Recipe JSON] -- GetRecipes

() "Store/Retrieve Item/Block" as StoreRetrieveBlockItem
[Crafting] --( StoreRetrieveBlockItem
[Inventory] -- StoreRetrieveBlockItem

() "Get Blocks for Gen" as BlocKGen
[Game World] --( BlocKGen
[Block] -- BlocKGen

() "Generate world from seed" as GenWorld
[Game World] -- GenWorld
GenWorld )-- [Game Menu]

() "Display World" as DisplayWorld
() "Display Player" as DisplayPlayer
() "Display UI" as DisplayUI

() "Display Crafting" as DisplayCrafting
() "Display Inventory" as DisplayInventory

[User Interface] --( DisplayCrafting
[User Interface] --( DisplayInventory
[Crafting] -- DisplayCrafting
[Inventory] -- DisplayInventory

[Camera] --( DisplayWorld
[Camera] --( DisplayPlayer
[Camera] --( DisplayUI
[Game World] -- DisplayWorld
[Player] -- DisplayPlayer
[User Interface] -- DisplayUI

() "Move Player" as MovePlayerWorld
[Player] --( MovePlayerWorld
[Game World] -- MovePlayerWorld

() "Move Camera on Player Move" as MovePlayerCamera
[Camera] -- MovePlayerCamera
[Player] --( MovePlayerCamera

() "Get Audio to Play" as playAudio
[Audio] -- playAudio
[Player] --( playAudio

() "Interface through Gym" as AgentInterface #ADD8E6
[AI Agent] --( AgentInterface
[Player] -- AgentInterface


@enduml