site_name: ScrumDog Millionaires

nav:
    - Home: index.md
    - Playing the default game: maingame.md
    - Using the Gym Agent: gymgame.md


theme:
  name: material
  logo: assets/scrumlogo.png
  favicon: assets/scrumlogo.png
  features:
    - navigation.sections
    - navigation.expand
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: cyan
      accent: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: cyan
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
   