name: CodeCov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Set up Python 3.9
       uses: actions/setup-python@v2
       with:
          python-version: 3.9
     - name: Install dependencies
       run: |
        pip install pygame
        pip install coverage
        pip install pygame_gui
        pip install numpy
        pip install perlin-noise
     - name: Generate Report
       run: |
        coverage run test.py
        coverage xml
     - name: Upload Coverage to Codecov
       uses: codecov/codecov-action@v2
       with:
         token: ${{ secrets.CODECOV_TOKEN }}
#ignore:
 #   -"soundHandler.py"
  
